name: darthcine
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672